# Generated by Django 2.2 on 2019-05-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=20)),
                ('rep', models.CharField(max_length=20)),
                ('Fich', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
