# Generated by Django 2.2 on 2019-05-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_cours',
            name='rep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
