# Generated by Django 2.2 on 2019-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0002_auto_20190501_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
