# Generated by Django 2.2 on 2019-05-01 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=40, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 15, 14, 38, 328169, tzinfo=utc), null=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.domaine')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.Question_Cours')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
