# Generated by Django 2.2 on 2019-05-01 19:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0006_auto_20190501_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_cours',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.Question_cours'),
        ),
        migrations.AlterField(
            model_name='events_cours',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 1, 19, 34, 16, 957141, tzinfo=utc), null=True),
        ),
    ]
