# Generated by Django 2.2 on 2019-05-04 00:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0007_auto_20190501_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaine',
            name='Domain_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='events_cours',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.Question_cours'),
        ),
        migrations.AlterField(
            model_name='events_cours',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 4, 0, 50, 30, 720320, tzinfo=utc), null=True),
        ),
    ]
