# Generated by Django 2.2 on 2019-05-04 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0008_auto_20190504_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_cours',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.Question_cours'),
        ),
        migrations.AlterField(
            model_name='events_cours',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 4, 1, 16, 44, 867295, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question_cours',
            name='Fich',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
