# Generated by Django 2.2 on 2019-05-17 18:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0009_auto_20190504_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_cours',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenement.Question_cours'),
        ),
        migrations.AlterField(
            model_name='events_cours',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 17, 18, 51, 5, 285158, tzinfo=utc), null=True),
        ),
    ]
